Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog Posts
      url: /blog
      weight: 1
Paginate: 3
baseURL: https://4lch4.com
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  about:
    content: |
      I'm a software developer with a fondness for REST APIs. I have a Bachelor's degree in **Information Technology - Programming** from the **University of Arkansas Fort Smith**.
      
      I've been writing code since 2009 when one of my high school teachers introduced me to Visual Basic.
    enable: true
    image: /images/My-Avatar.png
    skills:
      enable: true
      items:
        - TypeScript
        - JavaScript
        - PowerShell
        - Java
        - Docker
        - Azure DevOps
        - GitHub Actions
        - Jenkins
        - Git
        - Linux
        - CSS
        - HTML5
        - Kubernetes
      title: "These are the skills, languages, and technologies I am most proficient with:"
    title: About Me
  achievements:
    enable: true
    items:
      - content: |
          While working at J.B. Hunt I helped with a cloud-migration from Microsoft
          Azure to Google Cloud Platform. We managed to move faster, and without
          disruptions, than any company Google had worked with, outside their own
          efforts.
        title: Fastest Cloud Migration Outside Google
      - content: Developed a site to display health status of major applications.
        title: "2019 J.B. Hunt Hackathon E&T Award"
      - content: |
          Further developed status page for external customers. Gained support of
          C-Level executives which provided full funding for the project.
        title: "2020 J.B. Hunt Hackathon E&T Award"
  contact:
    btnName: E-Mail Me
    content: |
      My inbox is always open but I rarely check it. If you'd like to reach out,
      please reach out over Twitter, Discord, or another method on
      <a href="https://4lch4.social" target="_blank">4lch4.social</a>.
    email: "hey@4lch4.email"
    enable: true
  description: "This website shall serve as a collection of my blog posts, projects (old and new), and other things I'm interested in."
  education:
    enable: true
    items:
      - date: Aug 2011 - Mar 2015
        school:
          name: University of Arkansas Fort Smith
          url: https://uafs.edu
        title: Bachelors - Information Technology - Programming
  experience:
    enable: true
    items:
      - company: JB Hunt
        companyUrl: https://www.jbhunt.com
        content: |
          I am currently a Senior Operations Engineer for the NOC at JBH. Some of my responsibilities include, but are not limited to:
          
          - Develop web applications and API services that provided value to daily operations and reporting.
          - Provide support and training for Dynatrace and our other monitoring tools as an SME for each of the products.
          - Teach NOC about programming practices such as Pull Requests, agile development, CICD pipelines, and much more.
        date: Feb 2020 - Present
        job: Senior Operations Engineer
      - company: JB Hunt
        companyUrl: https://www.jbhunt.com
        content: |
          I started at J.B. Hunt as a Contractor in the position of NOC Engineer. While I was a contractor, some of my responsibilities included:
          
          - Developed a number of small utilities to be used by the NOC that made handling operations much easier.
          - Monitored operations health via software such as Dynatrace, ExtraHop, etc., to keep servers, services, and websites functional and healthy for business use.
          - Networked with various teams to ensure proper support and simplify any existing processes.
        date: Jan 2019 - Feb 2020
        job: NOC Engineer
      - company: "4lch4 Industries LLC"
        companyUrl: https://4lch4.industries
        content: |
          - Work with a number of clients to create, maintain, or simply improve, their company websites.
          - Became a top-10% contractor with an award from Upwork, the main site I used for gaining new clients.
          - Retained a number of regular clients while developing new relationships with new clients.
        date: Feb 2018 - Jan 2019
        job: Freelancer
      - company: SAPIEN Technologies
        companyUrl: https://www.sapien.com/
        content: |
          - Tested each new iteration of our software to ensure a high-level of quality.
          - Created an Android app that was based on an iOS app the company had (iPowerShell).
          - Provided front-line support for customers via a forum and dedicated support ticket system.
        date: Aug 2015 - May 2017
        job: Junior Software Test Engineer
  favicon: /images/favicon.png
  footer:
    socialNetworks:
      facebook: https://facebook.com/4lch4
      github: https://github.com/4lch4
      instagram: https://www.instagram.com/4lch4/
      linkedin: https://linkedin.com/in/devin-leaman-49622429
      twitter: https://twitter.com/4lch4
  hero:
    content: |
      Less self-deprecating, I'm a software developer and operations engineer by
      trade. I can write front and backend code, manage servers, create CICD
      pipelines, and much more.
    enable: true
    image: /images/My-Avatar.png
    intro: "Hey, my name is"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/4lch4
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/devin-leaman-49622429
        - icon: fab fa-twitter
          url: https://twitter.com/4lch4
        - icon: fab fa-instagram
          url: https://www.instagram.com/4lch4/
        - icon: fab fa-facebook
          url: https://facebook.com/4lch4
        - icon: fab fa-dev
          url: https://dev.to/4lch4
    subtitle: "I'm just some guy who likes making and fixing things that usually involve a keyboard and/or a mouse."
    title: "4lch4 (Al-kuh"
  projects:
    enable: true
    items:
      - badges:
          - Dhall
          - Hugo
          - GitHub
          - Vercel
        content: |
          My homepage on the internet.
          
          Photo by Markus Spiske on Unsplash.
        featured:
          link: https://github.com/4lch4/4lch4.com
          name: Source Code
        image: /images/Homepage-00.jpeg
        links:
          - icon: fas fa-house-user
            url: https://4lch4.com
        title: "4lch4.com"
      - badges:
          - GitHub
          - Hugo
          - Vercel
        content: |
          A collection of links to my various public "social media" accounts.
          
          Photo by Alexander Shatov on Unsplash.
        featured:
          link: https://github.com/4lch4/4lch4.social
          name: Source Code
        image: /images/Socials.jpeg
        links:
          - icon: fas fa-link
            url: https://4lch4.social
        title: "4lch4.social"
  title: "4lch4's Homepage"
theme: hugo-profile
title: "4lch4's Homepage"
